      

      .section data

       NOP           
       LD BC,23561      
       LD (BC),A     
       INC BC        
       INC B         
       DEC B         
       LD B,23        
       RLCA          
       ADD HL,BC     
       LD A,(BC)     
       DEC BC        
       INC C         
       DEC C         
       LD C,23        
       RRCA          
       DJNZ label0
label0:
       LD DE,23561      
       LD (DE),A     
       INC DE        
       INC D         
       DEC D         
       LD D,23        
       RLA           
label2:
       JR label2
       ADD HL,DE     
       LD A,(DE)     
       DEC DE        
       INC E         
       DEC E         
       LD E,23        
       RRA           
       JR NZ,label3
       LD HL,23561      
       LD (23561),HL    
       INC HL        
       INC H         
       DEC H         
       LD H,23        
       DAA           
label3:
       JR Z,label3
       ADD HL,HL     
       LD HL,(23561)    
       DEC HL        
       INC L         
       DEC L         
       LD L,23        
       CPL           
       JR NC,label3
       LD SP,23561      
       LD (23561),A     
       INC SP        
       INC (HL)      
       DEC (HL)      
       LD (HL),23     
       SCF           
label4:
       JR C,label4
       ADD HL,SP     
       LD A,(23561)     
       DEC SP        
       INC A         
       DEC A         
       LD A,23        
       CCF           
       LD B,B        
       LD B,C        
       LD B,D        
       LD B,E        
       LD B,H        
       LD B,L        
       LD B,(HL)     
       LD B,A        
       LD C,B        
       LD C,C        
       LD C,D        
       LD C,E        
       LD C,H        
       LD C,L        
       LD C,(HL)     
       LD C,A        
       LD D,B        
       LD D,C        
       LD D,D        
       LD D,E        
       LD D,H        
       LD D,L        
       LD D,(HL)     
       LD D,A        
       LD E,B        
       LD E,C        
       LD E,D        
       LD E,E        
       LD E,H        
       LD E,L        
       LD E,(HL)     
       LD E,A        
       LD H,B        
       LD H,C        
       LD H,D        
       LD H,E        
       LD H,H        
       LD H,L        
       LD H,(HL)     
       LD H,A        
       LD L,B        
       LD L,C        
       LD L,D        
       LD L,E        
       LD L,H        
       LD L,L        
       LD L,(HL)     
       LD L,A        
       LD (HL),B     
       LD (HL),C     
       LD (HL),D     
       LD (HL),E     
       LD (HL),H     
       LD (HL),L     
       HALT          
       LD (HL),A     
       LD A,B        
       LD A,C        
       LD A,D        
       LD A,E        
       LD A,H        
       LD A,L        
       LD A,(HL)     
       LD A,A        
       ADD A,B       
       ADD A,C       
       ADD A,D       
       ADD A,E       
       ADD A,H       
       ADD A,L       
       ADD A,(HL)    
       ADD A,A       
       ADC A,B       
       ADC A,C       
       ADC A,D       
       ADC A,E       
       ADC A,H       
       ADC A,L       
       ADC A,(HL)    
       ADC A,A       
       SUB B         
       SUB C         
       SUB D         
       SUB E         
       SUB H         
       SUB L         
       SUB (HL)      
       SUB A         
       SBC A,B       
       SBC A,C       
       SBC A,D       
       SBC A,E       
       SBC A,H       
       SBC A,L       
       SBC A,(HL)    
       SBC A,A       
       AND B         
       AND C         
       AND D         
       AND E         
       AND H         
       AND L         
       AND (HL)      
       AND A         
       XOR B         
       XOR C         
       XOR D         
       XOR E         
       XOR H         
       XOR L         
       XOR (HL)      
       XOR A         
       OR B          
       OR C          
       OR D          
       OR E          
       OR H          
       OR L          
       OR (HL)       
       OR A          
       CP B          
       CP C          
       CP D          
       CP E          
       CP H          
       CP L          
       CP (HL)       
       CP A          
       RET NZ        
       POP BC        
       JP NZ,23561    
       JP 23561       
       CALL NZ,23561  
       PUSH BC       
       ADD A,23       
       RST 0
       RET Z         
       RET           
       JP Z,23561     
       CALL Z,23561   
       CALL 23561     
       ADC A,23       
       RST 8        
       RET NC        
       POP DE        
       JP NC,23561    
       OUT (23),A     
       CALL NC,23561  
       PUSH DE       
       SUB 23         
       RST 16
       RET C         
       JP C,23561     
       IN A,(23)      
       CALL C,23561   
       SBC A,23
       RST 24
       RET PO
       POP HL
       JP PO,23561
       EX (SP),HL
       CALL PO,23561
       PUSH HL
       AND 23
       RST 32
       RET PE
       JP (HL)
       JP PE,23561
       EX DE,HL
       CALL PE,23561
       XOR 23
       RST 40
       RET P
       POP AF
       JP P,23561
       DI
       CALL P,23561
       PUSH AF
       OR 23
       RST 48
       RET M
       LD SP,HL
       JP M,23561
       EI
       CALL M,23561
       CP 23
       RST 56
