; Z180 test opcodes


        .section        data


        defc    n = 23
        
        in0     a,(n)
        in0     b,(n)
        in0     c,(n)
        in0     d,(n)
        in0     e,(n)
        in0     h,(n)
        in0     l,(n)
        mult     bc
        mult     de
        mult     hl
        mult     sp
        otdm 
        otdmr
        otim 
        otimr
        out0	(n),a
        out0	(n),b
        out0	(n),c
        out0	(n),d
        out0	(n),e
        out0	(n),h
        out0	(n),l
        slp
        tst     a 
        tst     b 
        tst     c 
        tst     d 
        tst     e 
        tst     h 
        tst     l 
        tst     n
        tst     (hl)
        tstio   n 
      

      .section data
 
       NOP           
       LD BC,23561      
       LD (BC),A     
       INC BC        
       INC B         
       DEC B         
       LD B,23        
       RLCA          
       EX AF,AF'
       ADD HL,BC     
       LD A,(BC)     
       DEC BC        
       INC C         
       DEC C         
       LD C,23        
       RRCA          
       DJNZ label0
label0:
       LD DE,23561      
       LD (DE),A     
       INC DE        
       INC D         
       DEC D         
       LD D,23        
       RLA           
label2:
       JR label2
       ADD HL,DE     
       LD A,(DE)     
       DEC DE        
       INC E         
       DEC E         
       LD E,23        
       RRA           
       JR NZ,label3
       LD HL,23561      
       LD (23561),HL    
       INC HL        
       INC H         
       DEC H         
       LD H,23        
       DAA           
label3:
       JR Z,label3
       ADD HL,HL     
       LD HL,(23561)    
       DEC HL        
       INC L         
       DEC L         
       LD L,23        
       CPL           
       JR NC,label3
       LD SP,23561      
       LD (23561),A     
       INC SP        
       INC (HL)      
       DEC (HL)      
       LD (HL),23     
       SCF           
label4:
       JR C,label4
       ADD HL,SP     
       LD A,(23561)     
       DEC SP        
       INC A         
       DEC A         
       LD A,23        
       CCF           
       LD B,B        
       LD B,C        
       LD B,D        
       LD B,E        
       LD B,H        
       LD B,L        
       LD B,(HL)     
       LD B,A        
       LD C,B        
       LD C,C        
       LD C,D        
       LD C,E        
       LD C,H        
       LD C,L        
       LD C,(HL)     
       LD C,A        
       LD D,B        
       LD D,C        
       LD D,D        
       LD D,E        
       LD D,H        
       LD D,L        
       LD D,(HL)     
       LD D,A        
       LD E,B        
       LD E,C        
       LD E,D        
       LD E,E        
       LD E,H        
       LD E,L        
       LD E,(HL)     
       LD E,A        
       LD H,B        
       LD H,C        
       LD H,D        
       LD H,E        
       LD H,H        
       LD H,L        
       LD H,(HL)     
       LD H,A        
       LD L,B        
       LD L,C        
       LD L,D        
       LD L,E        
       LD L,H        
       LD L,L        
       LD L,(HL)     
       LD L,A        
       LD (HL),B     
       LD (HL),C     
       LD (HL),D     
       LD (HL),E     
       LD (HL),H     
       LD (HL),L     
       HALT          
       LD (HL),A     
       LD A,B        
       LD A,C        
       LD A,D        
       LD A,E        
       LD A,H        
       LD A,L        
       LD A,(HL)     
       LD A,A        
       ADD A,B       
       ADD A,C       
       ADD A,D       
       ADD A,E       
       ADD A,H       
       ADD A,L       
       ADD A,(HL)    
       ADD A,A       
       ADC A,B       
       ADC A,C       
       ADC A,D       
       ADC A,E       
       ADC A,H       
       ADC A,L       
       ADC A,(HL)    
       ADC A,A       
       SUB B         
       SUB C         
       SUB D         
       SUB E         
       SUB H         
       SUB L         
       SUB (HL)      
       SUB A         
       SBC A,B       
       SBC A,C       
       SBC A,D       
       SBC A,E       
       SBC A,H       
       SBC A,L       
       SBC A,(HL)    
       SBC A,A       
       AND B         
       AND C         
       AND D         
       AND E         
       AND H         
       AND L         
       AND (HL)      
       AND A         
       XOR B         
       XOR C         
       XOR D         
       XOR E         
       XOR H         
       XOR L         
       XOR (HL)      
       XOR A         
       OR B          
       OR C          
       OR D          
       OR E          
       OR H          
       OR L          
       OR (HL)       
       OR A          
       CP B          
       CP C          
       CP D          
       CP E          
       CP H          
       CP L          
       CP (HL)       
       CP A          
       RET NZ        
       POP BC        
       JP NZ,23561    
       JP 23561       
       CALL NZ,23561  
       PUSH BC       
       ADD A,23       
       RST 0
       RET Z         
       RET           
       JP Z,23561     
       RLC B         
       RLC C         
       RLC D         
       RLC E         
       RLC H         
       RLC L         
       RLC (HL)      
       RLC A         
       RRC B         
       RRC C         
       RRC D         
       RRC E         
       RRC H         
       RRC L         
       RRC (HL)      
       RRC A         
       RL B          
       RL C          
       RL D          
       RL E          
       RL H          
       RL L          
       RL (HL)       
       RL A          
       RR B          
       RR C          
       RR D          
       RR E          
       RR H          
       RR L          
       RR (HL)       
       RR A          
       SLA B         
       SLA C         
       SLA D         
       SLA E         
       SLA H         
       SLA L         
       SLA (HL)      
       SLA A         
       SRA B         
       SRA C         
       SRA D         
       SRA E         
       SRA H         
       SRA L         
       SRA (HL)      
       SRA A         
       SRL B         
       SRL B         
       SRL C         
       SRL D         
       SRL E         
       SRL H         
       SRL L         
       SRL (HL)      
       SRL A         
       BIT 0,B       
       BIT 0,C       
       BIT 0,D       
       BIT 0,E       
       BIT 0,H       
       BIT 0,L       
       BIT 0,(HL)    
       BIT 0,A       
       BIT 1,B       
       BIT 1,C       
       BIT 1,D       
       BIT 1,E       
       BIT 1,H       
       BIT 1,L       
       BIT 1,(HL)    
       BIT 1,A       
       BIT 2,B       
       BIT 2,C       
       BIT 2,D       
       BIT 2,E       
       BIT 2,H       
       BIT 2,L       
       BIT 2,(HL)    
       BIT 2,A       
       BIT 3,B       
       BIT 3,C       
       BIT 3,D       
       BIT 3,E       
       BIT 3,H       
       BIT 3,L       
       BIT 3,(HL)    
       BIT 3,A       
       BIT 4,B       
       BIT 4,C       
       BIT 4,D       
       BIT 4,E       
       BIT 4,H       
       BIT 4,L       
       BIT 4,(HL)    
       BIT 4,A       
       BIT 5,B       
       BIT 5,C       
       BIT 5,D       
       BIT 5,E       
       BIT 5,H       
       BIT 5,L       
       BIT 5,(HL)    
       BIT 5,A       
       BIT 6,B       
       BIT 6,C       
       BIT 6,D       
       BIT 6,E       
       BIT 6,H       
       BIT 6,L       
       BIT 6,(HL)    
       BIT 6,A       
       BIT 7,B       
       BIT 7,C       
       BIT 7,D       
       BIT 7,E       
       BIT 7,H       
       BIT 7,L       
       BIT 7,(HL)    
       BIT 7,A       
       RES 0,B       
       RES 0,C       
       RES 0,D       
       RES 0,E       
       RES 0,H       
       RES 0,L       
       RES 0,(HL)    
       RES 0,A       
       RES 1,B       
       RES 1,C       
       RES 1,D       
       RES 1,E       
       RES 1,H       
       RES 1,L       
       RES 1,(HL)    
       RES 1,A       
       RES 2,B       
       RES 2,C       
       RES 2,D       
       RES 2,E       
       RES 2,H       
       RES 2,L       
       RES 2,(HL)    
       RES 2,A       
       RES 3,B       
       RES 3,C       
       RES 3,D       
       RES 3,E       
       RES 3,H       
       RES 3,L       
       RES 3,(HL)    
       RES 3,A       
       RES 4,B       
       RES 4,C       
       RES 4,D       
       RES 4,E       
       RES 4,H       
       RES 4,L       
       RES 4,(HL)    
       RES 4,A       
       RES 5,B       
       RES 5,C       
       RES 5,D       
       RES 5,E       
       RES 5,H       
       RES 5,L       
       RES 5,(HL)    
       RES 5,A       
       RES 6,B       
       RES 6,C       
       RES 6,D       
       RES 6,E       
       RES 6,H       
       RES 6,L       
       RES 6,(HL)    
       RES 6,A       
       RES 7,B       
       RES 7,C       
       RES 7,D       
       RES 7,E       
       RES 7,H       
       RES 7,L       
       RES 7,(HL)    
       RES 7,A       
       SET 0,B       
       SET 0,C       
       SET 0,D       
       SET 0,E       
       SET 0,H       
       SET 0,L       
       SET 0,(HL)    
       SET 0,A       
       SET 1,B       
       SET 1,C       
       SET 1,D       
       SET 1,E       
       SET 1,H       
       SET 1,L       
       SET 1,(HL)    
       SET 1,A       
       SET 2,B       
       SET 2,C       
       SET 2,D       
       SET 2,E       
       SET 2,H       
       SET 2,L       
       SET 2,(HL)    
       SET 2,A       
       SET 3,B       
       SET 3,C       
       SET 3,D       
       SET 3,E       
       SET 3,H       
       SET 3,L       
       SET 3,(HL)    
       SET 3,A       
       SET 4,B       
       SET 4,C       
       SET 4,D       
       SET 4,E       
       SET 4,H       
       SET 4,L       
       SET 4,(HL)    
       SET 4,A       
       SET 5,B       
       SET 5,C       
       SET 5,D       
       SET 5,E       
       SET 5,H       
       SET 5,L       
       SET 5,(HL)    
       SET 5,A       
       SET 6,B       
       SET 6,C       
       SET 6,D       
       SET 6,E       
       SET 6,H       
       SET 6,L       
       SET 6,(HL)    
       SET 6,A       
       SET 7,B       
       SET 7,C       
       SET 7,D       
       SET 7,E       
       SET 7,H       
       SET 7,L       
       SET 7,(HL)    
       SET 7,A       
       CALL Z,23561   
       CALL 23561     
       ADC A,23       
       RST 8        
       RET NC        
       POP DE        
       JP NC,23561    
       OUT (23),A     
       CALL NC,23561  
       PUSH DE       
       SUB 23         
       RST 16
       RET C         
       EXX           
       JP C,23561     
       IN A,(23)      
       CALL C,23561   
       ADD IX,BC     
       ADD IX,DE
       LD IX,23561
       LD (23561),IX
       INC IX
       ADD IX,IX
       LD IX,(23561)
       DEC IX
       INC (IX+10)
       DEC (IX+10)
       LD (IX+10),23
       ADD IX,SP
       LD B,(IX+10)
       LD C,(IX+10)
       LD D,(IX+10)
       LD E,(IX+10)
       LD H,(IX+10)
       LD L,(IX+10)
       LD (IX+10),B
       LD (IX+10),C
       LD (IX+10),D
       LD (IX+10),E
       LD (IX+10),H
       LD (IX+10),L
       LD (IX+10),A
       LD A,(IX+10)
       ADD A,(IX+10)
       ADC A,(IX+10)
       SUB (IX+10)
       SBC A,(IX+10)
       AND (IX+10)
       XOR (IX+10)
       OR (IX+10)
       CP (IX+10)
       RLC (IX+10)
       RRC (IX+10)
       RL (IX+10)
       RR (IX+10)
       SLA (IX+10)
       SRA (IX+10)
       SRL (IX+10)
       BIT 0,(IX+10)
       BIT 1,(IX+10)
       BIT 2,(IX+10)
       BIT 3,(IX+10)
       BIT 4,(IX+10)
       BIT 5,(IX+10)
       BIT 6,(IX+10)
       BIT 7,(IX+10)
       RES 0,(IX+10)
       RES 1,(IX+10)
       RES 2,(IX+10)
       RES 3,(IX+10)
       RES 4,(IX+10)
       RES 5,(IX+10)
       RES 6,(IX+10)
       RES 7,(IX+10)
       SET 0,(IX+10)
       SET 1,(IX+10)
       SET 2,(IX+10)
       SET 3,(IX+10)
       SET 4,(IX+10)
       SET 5,(IX+10)
       SET 6,(IX+10)
       SET 7,(IX+10)
       POP IX
       EX (SP),IX
       PUSH IX
       JP (IX)
       LD SP,IX
       SBC A,23
       RST 24
       RET PO
       POP HL
       JP PO,23561
       EX (SP),HL
       CALL PO,23561
       PUSH HL
       AND 23
       RST 32
       RET PE
       JP (HL)
       JP PE,23561
       EX DE,HL
       CALL PE,23561
       IN B,(C)
       OUT (C),B
       SBC HL,BC
       LD (23561),BC
       NEG
       RETN
       IM 0
       LD I,A
       IN C,(C)
       OUT (C),C
       ADC HL,BC
       LD BC,(23561)
       RETI
       LD R,A
       IN D,(C)
       OUT (C),D
       SBC HL,DE
       LD (23561),DE
       IM 1
       LD A,I
       IN E,(C)
       OUT (C),E
       ADC HL,DE
       LD DE,(23561)
       IM 2
       LD A,R
       IN H,(C)
       OUT (C),H
       SBC HL,HL
       LD (23561),HL
       RRD
       IN L,(C)
       OUT (C),L
       ADC HL,HL
       LD HL,(23561)
       RLD
       SBC HL,SP
       LD (23561),SP    
       IN A,(C)
       OUT (C),A
       ADC HL,SP
       LD SP,(23561)
       LDI
       CPI
       INI
       OUTI
       LDD
       CPD
       IND
       OUTD
       LDIR
       CPIR
       INIR
       OTIR
       LDDR
       CPDR
       INDR
       OTDR
       XOR 23
       RST 40
       RET P
       POP AF
       JP P,23561
       DI
       CALL P,23561
       PUSH AF
       OR 23
       RST 48
       RET M
       LD SP,HL
       JP M,23561
       EI
       CALL M,23561
       ADD IY,BC
       ADD IY,DE
       LD IY,23561
       LD (23561),IY
       INC IY
       ADD IY,IY
       LD IY,(23561)
       DEC IY
       INC (IY+10)
       DEC (IY+10)
       LD (IY+10),23
       ADD IY,SP
       LD B,(IY+10)
       LD C,(IY+10)
       LD D,(IY+10)
       LD E,(IY+10)
       LD H,(IY+10)
       LD L,(IY+10)
       LD (IY+10),B
       LD (IY+10),C
       LD (IY+10),D
       LD (IY+10),E
       LD (IY+10),H
       LD (IY+10),L
       LD (IY+10),A
       LD A,(IY+10)
       ADD A,(IY+10)
       ADC A,(IY+10)
       SUB (IY+10)
       SBC A,(IY+10)
       AND (IY+10)
       XOR (IY+10)
       OR (IY+10)
       CP (IY+10)
       RLC (IY+10)
       RRC (IY+10)
       RL (IY+10)
       RR (IY+10)
       SLA (IY+10)
       SRA (IY+10)
       SRL (IY+10)
       BIT 0,(IY+10)
       BIT 1,(IY+10)
       BIT 2,(IY+10)
       BIT 3,(IY+10)
       BIT 4,(IY+10)
       BIT 5,(IY+10)
       BIT 6,(IY+10)
       BIT 7,(IY+10)
       RES 0,(IY+10)
       RES 1,(IY+10)
       RES 2,(IY+10)
       RES 3,(IY+10)
       RES 4,(IY+10)
       RES 5,(IY+10)
       RES 6,(IY+10)
       RES 7,(IY+10)
       SET 0,(IY+10)
       SET 1,(IY+10)
       SET 2,(IY+10)
       SET 3,(IY+10)
       SET 4,(IY+10)
       SET 5,(IY+10)
       SET 6,(IY+10)
       SET 7,(IY+10)
       POP IY
       EX (SP),IY
       PUSH IY
       JP (IY)
       LD SP,IY
       CP 23
       RST 56
